Feature
xdx505/TeleportWizard pull request #1
Opened 2021-02-22 14:10 UTC by xdx505

2021-02-23 08:40 UTC, LionZXY commented
> feature
Лучше, конечно, более осмысленно ветку называть

2021-02-23 09:01 UTC, LionZXY requested changes

2021-02-23 09:15 UTC, xdx505 commented on src/main/java/com/xdx505/teleportitems/utils/TeleportUtils.java
> +    public static void teleport(World worldIn, PlayerEntity playerIn, DimensionBlockPos pos) {
Так worldIn это не куда игрок телепортируется, это мир, в котором он находится. Место куда он телепортируется  - pos.

2021-02-23 09:16 UTC, xdx505 commented on src/main/java/com/xdx505/teleportitems/utils/TeleportUtils.java
> +            //TODO change dimension type
В данном варианте клиент крашится, если телепортироваться из ада в верхний мир, например.

2021-02-23 09:20 UTC, xdx505 commented on src/main/java/com/xdx505/teleportitems/utils/TeleportUtils.java
> +        if (!playerIn.getEntityWorld().getDimensionType().equals(pos.getDimensionType())) {
Не уверен. Кейсом смены мира я ещё не занимался совсем.

2021-02-23 16:18 UTC, xdx505 commented on src/main/java/com/xdx505/teleportitems/utils/TeleportUtils.java
> +        DimensionBlockPos emptyPosition = WorldBlockHelper.findEmptySpaceByY(worldIn, pos);
Понял, исправил.

2021-02-23 16:21 UTC, xdx505 commented on src/main/java/com/xdx505/teleportitems/utils/TeleportUtils.java
> +        SoundEvent event = new SoundEvent(new ResourceLocation("entity.enderman.teleport"));
Хорошая идея! SoundEvents.ENTITY_ENDERMAN_TELEPORT

2021-02-23 17:34 UTC, xdx505 commented on src/main/java/com/xdx505/teleportitems/utils/DimensionBlockPos.java
> +    public DimensionBlockPos(DimensionType dimensionType, int X, int Y, int Z) {
Sory...

2021-02-23 18:03 UTC, xdx505 commented on src/main/java/com/xdx505/teleportitems/items/teleportation/TeleportDelayThread.java
> +                    entityPlayer.sendMessage(message, UUID.randomUUID());
Ok

2021-02-23 18:31 UTC, xdx505 commented on src/main/java/com/xdx505/teleportitems/items/teleportation/TeleportDelayThread.java
> +    final private int delay = 3;
Готово

2021-02-24 17:27 UTC, LionZXY approved these changes
LGTM

2021-02-24 17:36 UTC, merged